gantt
  dateFormat YYYY-MM-DD
  section Ehud Barak
    Hyatt 48Lex Stay          : eb1, 2015-02-01, 2015-03-30
    Beats Purchase            :milestone, eb2, 2015-02-24, 1d
    Wire Transfer Arrangement :milestone, eb3, 2015-02-23, 1d
    Yoni Koren Errand         : eb4, 2015-02-28, 2015-03-02
    Yoni Phone Call           :milestone, eb5, 2015-03-12, 1d
