gantt
  dateFormat YYYY-MM-DD
  section Ehud Barak
    Move to 66th Street Manhattan :milestone, eb1, 2015-08-09, 0d
  section Hyatt
    Hack Window                   : hy1, 2015-08-30, 2015-11-30
    48LEX Restructuring           :milestone, hy2, 2015-09-03, 0d
    Hack Discovery                :milestone, hy3, 2015-11-30, 0d
  section Baku
    FIDE World Cup                : bk1, 2015-09-10, 2015-10-05
    Jim Miller Visit              :milestone, bk2, 2015-09-18, 0d
    Sultan Bin Sulayem Visit      :milestone, bk3, 2015-09-19, 0d
